package ua.com.alevel.pharmbot.bot.state;

public enum PharmBotState {
    MEDS_SEARCH,
    MEDS_SEARCH_STARTED,
    MEDS_SEARCH_FINISHED,
    ASK_MEDICINE_NAME,
    MEDICINE_NAME_RECEIVED,
    ASK_ADDRESS,
    ASK_ABOUT_ADDRESS_CHANGE,
    ADDRESS_CHANGE_ANSWER_RECEIVED,
    ADDRESS_RECEIVED,
    INSTRUCTION_SEARCH,
    INSTRUCTION_SEARCH_STARTED,
    ASK_NEEDED_MEDICINE_NAME,
    NEEDED_MEDICINE_NAME_RECEIVED,
    ASK_MEDICINE_FORM_NAME,
    MEDICINE_FORM_NAME_RECEIVED,
    SEARCH_HISTORY_REQUEST,
    SHOW_MAIN_MENU,
    SHOW_HELP_MENU
}
